enyo.depends(
	"css/transitions.css",
	"source/supers/forms.simple.js",
	"source/supers/forms.list.js",
	"source/supers/crud.js",
	
	"source/controls/controls.autocomplete.js",
	"source/controls/controls.multiselect.js",
	"source/controls/controls.phoneBox.js",
	"source/controls/controls.reportViewer.js",
	"source/controls/controls.bindedField.js",
	
	"source/global/global.scrim.js",
	"source/global/cache.js",
	"source/global/global.utils.js",
	
	"source/cruds/crud.cattle.js",
	"source/cruds/crud.location.js",
	"source/cruds/crud.pen.js",
	"source/cruds/crud.rancher.js",
	"source/cruds/crud.rancherBilling.js",
	"source/cruds/crud.rancherContact.js",
	"source/cruds/crud.rancherUser.js",
	"source/cruds/crud.reception.js",
	"source/cruds/crud.enterpriseBilling.js",
	"source/cruds/crud.enterpriseContact.js",
	"source/cruds/crud.enterpriseRancher.js",
	"source/cruds/crud.enterpriseUser.js",
	"source/cruds/crud.user.js",
	
	"source/cache.rejects.js",
	"source/cache.feed.js",
	
	"source/catalogs/catalogs.list.rancher.js",
	"source/catalogs/catalogs.main.js",
	"source/catalogs/catalogs.menu.js",
	"source/catalogs/catalogs.rancher.billing.form.js",
	"source/catalogs/catalogs.rancher.contact.form.js",
	"source/catalogs/catalogs.rancher.enterprise.form.js",
	"source/catalogs/catalogs.rancher.person.form.js",
	"source/catalogs/catalogs.rancher.user.form.js",
	"source/catalogs/catalogs.ranchers.js",
	"source/catalogs/catalogs.ranchers.options.js",
	"source/catalogs/catalogs.enterprise.billing.form.js",
	"source/catalogs/catalogs.enterprise.contact.form.js",
	"source/catalogs/catalogs.enterprise.user.form.js",
	
	"source/operations/operations.reception.form.js",
	"source/operations/operations.pen.map.js",
	"source/userAdmin/useradmin.user.form.js",
	"source/operations/operations.feed.js",
	"source/receptions.inspections.js",
	
	"source/reports/reports.main.js",
	"source/reports/reports.select.js",					
	"source/reports/reports.filter.js",	
	"source/reports/reports.filter.by_date.js",
	
	"source/inspections.main.fs.js",
	"source/inspection.forecast.js",
	"source/cache.inspection.forecast.js",
	
	"source/main/login.js",
	"source/main/sisoprega.js",
	"source/main/main.menu.js",	
	"source/main/main.menu.options.js"
);