//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.10 at 01:56:35 PM MDT 
//


package jaxb.crud;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jaxb.crud package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jaxb.crud
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ResponseCrud }
     * 
     */
    public ResponseCrud createResponseCrud() {
        return new ResponseCrud();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseCustomop }
     * 
     */
    public ResponseCrud.ResponseCustomop createResponseCrudResponseCustomop() {
        return new ResponseCrud.ResponseCustomop();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseCustomop.Tuple }
     * 
     */
    public ResponseCrud.ResponseCustomop.Tuple createResponseCrudResponseCustomopTuple() {
        return new ResponseCrud.ResponseCustomop.Tuple();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseRead }
     * 
     */
    public ResponseCrud.ResponseRead createResponseCrudResponseRead() {
        return new ResponseCrud.ResponseRead();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseRead.Tuple }
     * 
     */
    public ResponseCrud.ResponseRead.Tuple createResponseCrudResponseReadTuple() {
        return new ResponseCrud.ResponseRead.Tuple();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseCreate }
     * 
     */
    public ResponseCrud.ResponseCreate createResponseCrudResponseCreate() {
        return new ResponseCrud.ResponseCreate();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseCustomop.Tuple.Att }
     * 
     */
    public ResponseCrud.ResponseCustomop.Tuple.Att createResponseCrudResponseCustomopTupleAtt() {
        return new ResponseCrud.ResponseCustomop.Tuple.Att();
    }

    /**
     * Create an instance of {@link ResponseCrud.ResponseRead.Tuple.Att }
     * 
     */
    public ResponseCrud.ResponseRead.Tuple.Att createResponseCrudResponseReadTupleAtt() {
        return new ResponseCrud.ResponseRead.Tuple.Att();
    }

}
