INSERT INTO cat_inspection_code(inspection_code_description) VALUES('ENFERMEDAD');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('HERIDA');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('OTRAS');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('DEBIL');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('CAIDO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('BOLA');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO ARETE TB');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO ARETE CASTRACION');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('TUMOR');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('TORCIDO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO FIERRO M');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO FIERRO MX');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('OJO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('RESECO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO COINCIDE');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('HERIDA ABIERTA');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('MASTITIS');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('CORTE');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('MUERTO');

/* Chihuahua (1) barnyards */
-- TODO: Retrieve from map pictures.
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E2', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E4', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E5', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E6', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E7', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E8', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E9', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E10', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E11', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E12', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E13', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E14', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E15', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E16', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E17', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E18', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E19', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E20', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E21', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E22', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E23', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E24', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E25', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E26', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E27', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E28', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E29', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E30', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E31', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E32', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D1', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D2', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D3', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D4', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D5', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D6', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D7', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D8', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D9', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D10', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D11', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D12', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D13', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D14', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D15', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D16', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D17', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D18', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D19', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D20', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D21', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D22', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D23', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D24', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D25', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D26', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D27', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D28', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D29', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D30', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D31', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D32', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C1', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C2', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C3', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C4', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C5', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C6', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C7', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C8', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C9', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C10', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C11', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C12', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C13', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C14', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C15', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C16', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C17', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C18', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C19', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C20', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C21', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C22', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C23', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C24', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C25', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C26', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C27', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C28', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C29', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C30', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C31', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C32', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B1', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B2', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B3', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B4', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B5', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B6', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B7', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B8', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B9', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B10', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B11', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B12', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B13', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B14', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B15', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B16', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B17', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B18', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B19', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B20', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B21', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B22', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B23', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B24', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B25', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B26', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B27', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B28', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B29', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B31', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A1', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A3', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A5', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A7', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A9', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A10', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A11', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A12', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A13', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A14', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A15', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A16', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A17', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A18', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A19', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A20', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A21', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A22', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A23', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A24', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A25', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A26', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A27', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A28', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A29', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A30', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A31', 1);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A32', 1);
/* Zona Sur (2) barnyards */
-- TODO: Retrieve from map pictures.
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E1', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E2', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E3', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E4', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E5', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E6', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E7', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('E8', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D1', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D2', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D4', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D5', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D6', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D7', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D8', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D10', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D11', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('D12', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C1', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C2', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C3', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C4', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C5', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C6', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C7', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C8', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C9', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C10', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C11', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('C12', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B1', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B2', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B3', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B4', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B5', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B6', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B7', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B8', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B9', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('B11', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A1', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A2', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A3', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A4', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A5', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A6', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A7', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('A8', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R1', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R2', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R3', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R4', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R5', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R6', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R7', 2);
INSERT INTO cat_barnyard(barnyard_code, zone_id) VALUES('R8', 2);

/* Food */
INSERT INTO cat_food(food_name) VALUES('Molida');
INSERT INTO cat_food(food_name) VALUES('Alfalfa');
INSERT INTO cat_food(food_name) VALUES('Avena');
INSERT INTO cat_food(food_name) VALUES('Concentrado');
INSERT INTO cat_food(food_name) VALUES('Maiz');

/* Locations  the first one is the default value in UI */
INSERT INTO cat_location(location_name) VALUES('Chihuahua');
INSERT INTO cat_location(location_name) VALUES('Aguascalientes');
INSERT INTO cat_location(location_name) VALUES('Baja California');
INSERT INTO cat_location(location_name) VALUES('Baja California Sur');
INSERT INTO cat_location(location_name) VALUES('Campeche');
INSERT INTO cat_location(location_name) VALUES('Chiapas');
INSERT INTO cat_location(location_name) VALUES('Coahuila');
INSERT INTO cat_location(location_name) VALUES('Colima');
INSERT INTO cat_location(location_name) VALUES('Distrito Federal');
INSERT INTO cat_location(location_name) VALUES('Durango');
INSERT INTO cat_location(location_name) VALUES('Estado de México');
INSERT INTO cat_location(location_name) VALUES('Guanajuato');
INSERT INTO cat_location(location_name) VALUES('Guerrero');
INSERT INTO cat_location(location_name) VALUES('Hidalgo');
INSERT INTO cat_location(location_name) VALUES('Jalisco');
INSERT INTO cat_location(location_name) VALUES('Michoacán');
INSERT INTO cat_location(location_name) VALUES('Morelos');
INSERT INTO cat_location(location_name) VALUES('Nayarit');
INSERT INTO cat_location(location_name) VALUES('Nuevo León');
INSERT INTO cat_location(location_name) VALUES('Oaxaca');
INSERT INTO cat_location(location_name) VALUES('Puebla');
INSERT INTO cat_location(location_name) VALUES('Querétaro');
INSERT INTO cat_location(location_name) VALUES('Quintana Roo');
INSERT INTO cat_location(location_name) VALUES('San Luis Potosí');
INSERT INTO cat_location(location_name) VALUES('Sinaloa');
INSERT INTO cat_location(location_name) VALUES('Sonora');
INSERT INTO cat_location(location_name) VALUES('Tabasco');
INSERT INTO cat_location(location_name) VALUES('Tamaulipas');
INSERT INTO cat_location(location_name) VALUES('Tlaxcala');
INSERT INTO cat_location(location_name) VALUES('Veracruz');
INSERT INTO cat_location(location_name) VALUES('Yucatán');
INSERT INTO cat_location(location_name) VALUES('Zacatecas');