INSERT INTO cat_inspection_code(inspection_code_description) VALUES('ENFERMEDAD');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('HERIDA');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('OTRAS');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('DEBIL');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('CAIDO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('BOLA');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO ARETE TB');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO ARETE CASTRACION');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('TUMOR');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('TORCIDO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO FIERRO M');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO FIERRO MX');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('OJO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('RESECO');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('NO COINCIDE');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('HERIDA ABIERTA');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('MASTITIS');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('CORTE');
INSERT INTO cat_inspection_code(inspection_code_description) VALUES('MUERTO');